# Generated by Django 3.0.7 on 2020-07-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testtext',
            field=models.TextField(blank=True, default='Test', max_length=500),
        ),
    ]
