# Generated by Django 3.0.7 on 2020-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_testtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='testtext',
        ),
        migrations.AddField(
            model_name='profile',
            name='opinion',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
