from django.utils.translation import ugettext_lazy as _


LangCodesDict = {'af': _('Afrikaans'), 'sq': _('Albanian'), 'am': _('Amharic'), 'ar': _('Arabic'), 'hy': _('Armenian'),
                 'az': _('Azerbaijani'), 'eu': _('Basque'), 'be': _('Belarusian'), 'bn': _('Bengali'), 'bs': _('Bosnian'),
                 'bg': _('Bulgarian'), 'ca': _('Catalan'), 'ceb': _('Cebuano'), 'ny': _('Chichewa'),
                 'zh-cn': _('Chinese (simplified)'), 'zh-tw': _('Chinese (traditional)'), 'co': _('Corsican'), 'hr': _('Croatian'),
                 'cs': _('Czech'), 'da': _('Danish'), 'nl': _('Dutch'), 'en': _('English'), 'eo': _('Esperanto'), 'et': _('Estonian'),
                 'tl': _('Filipino'), 'fi': _('Finnish'), 'fr': _('French'), 'fy': _('Frisian'), 'gl': _('Galician'), 'ka': _('Georgian'),
                 'de': _('German'), 'el': _('Greek'), 'gu': _('Gujarati'), 'ht': _('Haitian creole'), 'ha': _('Hausa'),
                 'haw': _('Hawaiian'), 'he': _('Hebrew'), 'hi': _('Hindi'), 'hmn': _('Hmong'), 'hu': _('Hungarian'), 'is': _('Icelandic'),
                 'ig': _('Igbo'), 'id': _('Indonesian'), 'ga': _('Irish'), 'it': _('Italian'), 'ja': _('Japanese'), 'jw': _('Javanese'),
                 'kn': _('Kannada'), 'kk': _('Kazakh'), 'km': _('Khmer'), 'ko': _('Korean'), 'ku': _('Kurdish (kurmanji)'),
                 'ky': _('Kyrgyz'), 'lo': _('Lao'), 'la': _('Latin'), 'lv': _('Latvian'), 'lt': _('Lithuanian'), 'lb': _('Luxembourgish'),
                 'mk': _('Macedonian'), 'mg': _('Malagasy'), 'ms': _('Malay'), 'ml': _('Malayalam'), 'mt': _('Maltese'), 'mi': _('Maori'),
                 'mr': _('Marathi'), 'mn': _('Mongolian'), 'my': _('Myanmar (burmese)'), 'ne': _('Nepali'), 'no': _('Norwegian'),
                 'ps': _('Pashto'), 'fa': _('Persian'), 'pl': _('Polish'), 'pt': _('Portuguese'), 'pa': _('Punjabi'),
                 'ro': _('Romanian'), 'ru': _('Russian'), 'sm': _('Samoan'), 'gd': _('Scots gaelic'), 'sr': _('Serbian'),
                 'st': _('Sesotho'), 'sn': _('Shona'), 'sd': _('Sindhi'), 'si': _('Sinhala'), 'sk': _('Slovak'), 'sl': _('Slovenian'),
                 'so': _('Somali'), 'es': _('Spanish'), 'su': _('Sundanese'), 'sw': _('Swahili'), 'sv': _('Swedish'), 'tg': _('Tajik'),
                 'ta': _('Tamil'), 'te': _('Telugu'), 'th': _('Thai'), 'tr': _('Turkish'), 'uk': _('Ukrainian'), 'ur': _('Urdu'),
                 'ug': _('Uyghur'), 'uz': _('Uzbek'), 'vi': _('Vietnamese'), 'cy': _('Welsh'), 'xh': _('Xhosa'), 'yi': _('Yiddish'),
                 'yo': _('Yoruba'), 'zu': _('Zulu')}


LangCodes = [("", _("OFF")),
             ('af', _('Afrikaans')), ('sq', _('Albanian')), ('ar', _('Arabic')), ('hy', _('Armenian')),
             ('az', _('Azerbaijani')), ('eu', _('Basque')), ('be', _('Belarusian')), ('bn', _('Bengali')), ('bs', _('Bosnian')),
             ('bg', _('Bulgarian')), ('ca', _('Catalan')), ('ceb', _('Cebuano')), ('ny', _('Chichewa')),
             ('zh-cn', _('Chinese (simplified)')), ('zh-tw', _('Chinese (traditional)')), ('co', _('Corsican')),
             ('hr', _('Croatian')), ('cs', _('Czech')), ('da', _('Danish')), ('nl', _('Dutch')), ('en', _('English')),
             ('eo', _('Esperanto')), ('et', _('Estonian')), ('tl', _('Filipino')), ('fi', _('Finnish')), ('fr', _('French')),
             ('gl', _('Galician')), ('ka', _('Georgian')), ('de', _('German')), ('el', _('Greek')),
             ('gu', _('Gujarati')), ('ht', _('Haitian creole')),  ('haw', _('Hawaiian')), ('he', _('Hebrew')),
             ('hi', _('Hindi')),  ('hu', _('Hungarian')), ('is', _('Icelandic')),
             ('id', _('Indonesian')), ('ga', _('Irish')), ('it', _('Italian')), ('ja', _('Japanese')), ('jw', _('Javanese')),
             ('kn', _('Kannada')), ('kk', _('Kazakh')), ('km', _('Khmer')), ('ko', _('Korean')), ('ku', _('Kurdish (kurmanji)')),
             ('ky', _('Kyrgyz')), ('lo', _('Lao')), ('la', _('Latin')), ('lv', _('Latvian')), ('lt', _('Lithuanian')),
             ('lb', _('Luxembourgish')), ('mk', _('Macedonian')), ('mg', _('Malagasy')), ('ms', _('Malay')), ('ml', _('Malayalam')),
             ('mt', _('Maltese')), ('mr', _('Marathi')), ('mn', _('Mongolian')), ('my', _('Myanmar (burmese)')),
             ('ne', _('Nepali')), ('no', _('Norwegian')), ('ps', _('Pashto')), ('fa', _('Persian')),
             ('pl', _('Polish')), ('pt', _('Portuguese')), ('pa', _('Punjabi')), ('ro', _('Romanian')), ('ru', _('Russian')),
             ('gd', _('Scots gaelic')), ('sr', _('Serbian')), ('st', _('Sesotho')),
             ('sd', _('Sindhi')), ('si', _('Sinhala')), ('sk', _('Slovak')), ('sl', _('Slovenian')), ('so', _('Somali')),
             ('es', _('Spanish')), ('su', _('Sundanese')), ('sw', _('Swahili')), ('sv', _('Swedish')), ('tg', _('Tajik')),
             ('ta', _('Tamil')), ('te', _('Telugu')), ('th', _('Thai')), ('tr', _('Turkish')), ('uk', _('Ukrainian')), ('ur', _('Urdu')),
             ('ug', _('Uyghur')), ('uz', _('Uzbek')), ('vi', _('Vietnamese')), ('cy', _('Welsh'))]

LangCodes0 = [
             ('af', _('Afrikaans')), ('sq', _('Albanian')), ('ar', _('Arabic')), ('hy', _('Armenian')),
             ('az', _('Azerbaijani')), ('eu', _('Basque')), ('be', _('Belarusian')), ('bn', _('Bengali')), ('bs', _('Bosnian')),
             ('bg', _('Bulgarian')), ('ca', _('Catalan')),  ('ny', _('Chichewa')),
             ('zh-cn', _('Chinese (simplified)')), ('zh-tw', _('Chinese (traditional)')), ('co', _('Corsican')),
             ('hr', _('Croatian')), ('cs', _('Czech')), ('da', _('Danish')), ('nl', _('Dutch')), ('en', _('English')),
             ('eo', _('Esperanto')), ('et', _('Estonian')), ('tl', _('Filipino')), ('fi', _('Finnish')), ('fr', _('French')),
             ('gl', _('Galician')), ('ka', _('Georgian')), ('de', _('German')), ('el', _('Greek')),
             ('gu', _('Gujarati')), ('ht', _('Haitian creole')),  ('haw', _('Hawaiian')), ('he', _('Hebrew')),
             ('hi', _('Hindi')),  ('hu', _('Hungarian')), ('is', _('Icelandic')),
             ('id', _('Indonesian')), ('ga', _('Irish')), ('it', _('Italian')), ('ja', _('Japanese')), ('jw', _('Javanese')),
             ('kn', _('Kannada')), ('kk', _('Kazakh')), ('km', _('Khmer')), ('ko', _('Korean')), ('ku', _('Kurdish (kurmanji)')),
             ('ky', _('Kyrgyz')), ('lo', _('Lao')), ('la', _('Latin')), ('lv', _('Latvian')), ('lt', _('Lithuanian')),
             ('lb', _('Luxembourgish')), ('mk', _('Macedonian')), ('mg', _('Malagasy')), ('ms', _('Malay')), ('ml', _('Malayalam')),
             ('mt', _('Maltese')), ('mr', _('Marathi')), ('mn', _('Mongolian')), ('my', _('Myanmar (burmese)')),
             ('ne', _('Nepali')), ('no', _('Norwegian')), ('ps', _('Pashto')), ('fa', _('Persian')),
             ('pl', _('Polish')), ('pt', _('Portuguese')), ('pa', _('Punjabi')), ('ro', _('Romanian')), ('ru', _('Russian')),
             ('gd', _('Scots gaelic')), ('sr', _('Serbian')), ('st', _('Sesotho')),
             ('sd', _('Sindhi')), ('si', _('Sinhala')), ('sk', _('Slovak')), ('sl', _('Slovenian')), ('so', _('Somali')),
             ('es', _('Spanish')), ('su', _('Sundanese')), ('sw', _('Swahili')), ('sv', _('Swedish')), ('tg', _('Tajik')),
             ('ta', _('Tamil')), ('te', _('Telugu')), ('th', _('Thai')), ('tr', _('Turkish')), ('uk', _('Ukrainian')), ('ur', _('Urdu')),
             ('ug', _('Uyghur')), ('uz', _('Uzbek')), ('vi', _('Vietnamese')), ('cy', _('Welsh'))]


