# Generated by Django 3.0.7 on 2020-06-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0004_auto_20200620_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfolder',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
