# Generated by Django 3.0.7 on 2020-06-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0005_auto_20200620_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='definition',
        ),
        migrations.AddField(
            model_name='multicard',
            name='definition',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
