# Generated by Django 3.0.7 on 2020-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0010_auto_20200629_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
