# Generated by Django 3.0.7 on 2020-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0011_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
