# Generated by Django 3.0.7 on 2020-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0014_card_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
