# Generated by Django 3.0.7 on 2020-07-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0015_auto_20200704_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='show',
        ),
    ]
