# Generated by Django 3.0.7 on 2020-07-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0016_remove_card_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='show_answer',
            field=models.BooleanField(default=True),
        ),
    ]
