# Generated by Django 3.0.7 on 2020-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0017_card_show_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardfolder',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multicard',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multicard',
            name='rates',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multicard',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
