# Generated by Django 3.0.7 on 2020-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0018_auto_20200704_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=False, upload_to='Cards/images/flags/'),
        ),
        migrations.AlterField(
            model_name='multicard',
            name='priority',
            field=models.SmallIntegerField(default=10),
        ),
    ]
