# Generated by Django 3.0.7 on 2020-07-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0019_auto_20200710_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
