# Generated by Django 3.0.7 on 2020-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0020_remove_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfolder',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
