# Generated by Django 3.0.7 on 2020-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0021_cardfolder_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfolder',
            name='show_multicard_comment',
            field=models.BooleanField(default=False),
        ),
    ]
